name: trilium
services:
  trilium:
    command: []
    container_name: trilium
    deploy:
      resources:
        reservations:
          memory: 256M
    image: triliumnext/trilium:v0.99.3
    ports:
    - target: 8080
      published: '8088'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /home/node/trilium-data
    network_mode: bridge
    privileged: false
x-casaos:
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/trilium/assets/icon.svg
  index: /
  port_map: '8088'
  scheme: http
  title: Trilium
  version: v0.99.3
