name: node-red
services:
  node-red:
    image: nodered/node-red:4.1.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: host
    ports:
    - target: 1880
      published: '1880'
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    container_name: node-red
x-casaos:
  main: node-red
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/node-red/assets/icon.svg
  title: Node-RED
  index: /
  port_map: '1880'
  version: 4.1.2
