name: index-tts-nvidia
services:
  index-tts-nvidia:
    image: icewhaletech/index-tts:2.0
    container_name: index-tts
    restart: unless-stopped
    ports:
    - target: 7860
      published: '7867'
      protocol: tcp
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          memory: 8G
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
x-casaos:
  title: Index-TTS(Nvidia GPU)
  main: index-tts-nvidia
  port_map: '7867'
  index: /
  scheme: http
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/index-tts-nvidia/assets/icon.svg
  version: '2.0'
