name: 9router
services:
  9router:
    image: decolua/9router:0.5.12@sha256:8dad0cbaa3c81d8a26b4deaf244bd527429796c99c3c3208c76dce61b74f3079
    container_name: 9router
    restart: unless-stopped
    ports:
    - target: 20128
      published: '20128'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /app/data
    environment:
      DATA_DIR: /app/data
      PORT: '20128'
      HOSTNAME: 0.0.0.0
      NODE_ENV: production
      INITIAL_PASSWORD: '123456'
      API_KEY_SECRET: endpoint-proxy-api-key-secret
      MACHINE_ID_SALT: endpoint-proxy-salt
      ENABLE_REQUEST_LOGS: 'false'
      OBSERVABILITY_ENABLED: 'true'
      AUTH_COOKIE_SECURE: 'false'
      REQUIRE_API_KEY: 'false'
      CLOUD_URL: https://9router.com
      NEXT_PUBLIC_CLOUD_URL: https://9router.com
x-casaos:
  app_id: com.decolua.9router
  main: 9router
  index: /
  port_map: '20128'
  scheme: http
  title:
    en_US: 9Router
    zh_CN: 9Router
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/com.decolua.9router/assets/icon.svg
  version: 0.5.12
