name: llama-factory-nvidia
services:
  llama-factory-nvidia:
    image: hiyouga/llamafactory:0.9.4
    container_name: llama-factory-nvidia
    ports:
    - target: 7860
      published: '18877'
      protocol: tcp
    tty: true
    stdin_open: true
    command:
    - llamafactory-cli
    - webui
    deploy:
      resources:
        reservations:
          memory: 6G
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
    restart: unless-stopped
x-casaos:
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/llama-factory-nvidia/assets/icon.svg
  title: LLaMA Factory(Nvidia GPU)
  index: /
  scheme: http
  main: llama-factory-nvidia
  port_map: '18877'
  version: 0.9.4
