name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge@sha256:2bcdd4d1a30f4ed31f1720f52e4cbcf94ec8094cdf89530068a20b94789bd0e7
    restart: always
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
x-casaos:
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/homebridge/assets/icon.svg
  title: Homebridge
  index: /
  port_map: '8581'
  version: latest
