name: uptimekuma
services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.16-alpine
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
    ports:
    - target: 3001
      published: '3001'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/app/data
      target: /app/data
    container_name: uptimekuma
x-casaos:
  main: uptimekuma
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/uptimekuma/assets/icon.svg
  title: Uptime Kuma
  index: /
  port_map: '3001'
  version: 1.23.16-alpine
