name: openhands
services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.49
    container_name: openhands
    environment:
    - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.49-nikolaik
    - WORKSPACE_MOUNT_PATH=/DATA/AppData/$AppID/workspace
    ports:
    - 13333:3000
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /DATA/AppData/$AppID/openhands:/.openhands
    - /DATA/AppData/$AppID/workspace:/opt/workspace_base
    stdin_open: true
    tty: true
x-casaos:
  main: openhands
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/openhands/assets/icon.svg
  scheme: http
  port_map: '13333'
  index: /
  title: OpenHands
  version: '0.59'
