name: peanut
services:
  peanut:
    image: brandawg93/peanut:5.19.1
    container_name: PeaNUT
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    ports:
    - target: 8080
      published: '8084'
      protocol: tcp
    environment:
      WEB_PORT: 8080
    deploy:
      resources:
        reservations:
          memory: 256M
x-casaos:
  title: PeaNUT
  icon: https://cdn.jsdelivr.net/gh/runui/zimaos-appstore@gh-pages/apps/peanut/assets/icon.svg
  main: peanut
  port_map: '8084'
  index: /
  scheme: http
  version: 5.19.1
